ADD: GET product detail info
wecode-bootcamp-korea/44-2nd-Dream-backend pull request #3
Opened 2023-04-24 13:34 UTC by walwald

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 상품 상세 페이지를 위한 GET 메서드에 대한 API 구현

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- query parameter를 통해 product id를 받아 GET 요청에 대해 prodcutDao에 상품 상세 정보 응답하는 함수 작성,

<br />

## :: 테스트 결과 이미지
![image](https://user-images.githubusercontent.com/120387100/234012081-dbe2e7b9-4344-42b2-ba56-9a299ce07707.png)

<br />

## :: 기타 질문 및 특이 사항

2023-04-25 03:18 UTC, Kang-kyunghun requested changes

2023-04-25 03:18 UTC, Kang-kyunghun commented on API/routes/productRouter.js
> +router.get('/:pid', productController.getProductDetail);
```suggestion
router.get('/:productId', productController.getProductDetail);
```

2023-04-25 03:18 UTC, Kang-kyunghun commented on API/services/productService.js
> +  productDetail.productAge = productDetail.productAge + '세 이상';
글자 붙이는 거는 front에서 하면 됩니다.
```suggestion
```

2023-04-25 03:18 UTC, Kang-kyunghun commented on API/services/productService.js
> +    ).toFixed(2) + '%';
해당 데이터는 왜 필요한 것인가요?

2023-04-25 03:18 UTC, Kang-kyunghun commented on API/utils/error.js
> +  console.log(err);
꼭 필요한 console.log인가요??
만약 꼭 필요하다면 console.err로 바꿔주세요.(아니면 지워주세요.)

2023-04-25 03:18 UTC, Kang-kyunghun commented on API/controllers/productController.js
> +  const { pid } = req.params;
```suggestion
  const { productId } = req.params;
```

2023-04-25 05:17 UTC, walwald commented on API/services/productService.js
> +    ).toFixed(2) + '%';
![image](https://user-images.githubusercontent.com/120387100/234180854-97d82cb1-0a5f-4fcf-985f-e253562672b2.png)

최근 거래가 아래 발매가 대비 premium의 percent를 표시하기 위함입니다!

2023-04-25 08:21 UTC, Kang-kyunghun requested changes

2023-04-25 08:21 UTC, Kang-kyunghun commented on API/services/productService.js
> +    ).toFixed(1) + '%';
여기도 %을 붙여서 주네요. 이것도 프론트에서 붙이면 될 것 같습니다.

2023-04-26 01:40 UTC, Kang-kyunghun requested changes

2023-04-26 01:40 UTC, Kang-kyunghun commented on API/models/productDao.js
> +const existingProduct = async (productId) => {
```suggestion
const isExistedProduct = async (productId) => {
```

2023-04-26 01:40 UTC, Kang-kyunghun commented on API/services/productService.js
> +  }
```suggestion
const getProductDetail = async (productId) => {
  const checkProductId = await productDao.existingProduct(productId);
  
  if (!checkProductId) {
    throw new BaseError('PRODUCT_DOES_NOT_EXIST', 404);
  }
```

2023-04-26 03:04 UTC, Kang-kyunghun commented
LGTM

2023-04-26 03:04 UTC, merged