[44기 송석준][ADD] 필터 기능 구현
wecode-bootcamp-korea/44-2nd-Dream-backend pull request #6
Opened 2023-04-25 06:22 UTC by songsong95

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
필터 기능 구현 추가

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
필터 기능 구현 추가

<br />

## :: 테스트 결과 이미지

file:///home/song137/%EC%82%AC%EC%A7%84/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7%202023-04-25%2014-59-25.png

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-04-25 06:23 UTC, songsong95 commented
![스크린샷 2023-04-25 14-59-25](https://user-images.githubusercontent.com/120084509/234191335-b3ff9440-f48b-4e3a-8d48-137fa2bbe0cd.png)

2023-04-25 08:40 UTC, Kang-kyunghun requested changes

2023-04-25 08:40 UTC, Kang-kyunghun commented on API/controllers/productController.js
> +  const { categoryId, sort, limit, offset } = req.query;
level하고 age로는 filtering 안 하나요?

2023-04-25 08:40 UTC, Kang-kyunghun commented on API/models/productDao.js
> +    const sortCondition = sortList[sort] || 'products.id';
오름차순과 내림차순을 선택할 수 있는 인자도 같이 받으면 좋을 것 같습니다.

```suggestion
    const sortList = {
      likede: 'likeCount',
      immediatebuyprice: 'immediateBuyPrice',
      review: 'reviewCount',
      premium: 'premiumPercent',
    };
    const sortOrder = {
      desc: "DESC"
      asc: "ASC"
    }
    const sortCondition = sortList[sort] ? `${sortList[sort]} ${sortOrder[sortOrder]}` : 'products.id';
```

2023-04-26 03:04 UTC, Kang-kyunghun requested changes

2023-04-26 03:04 UTC, Kang-kyunghun commented on API/controllers/productController.js
> +    req.query;
```suggestion
  const {
    categoryId, 
    ageId, 
    levelId, 
    sort, 
    sortorder, 
    limit, 
    offset 
  } = req.query;
```

2023-04-26 03:04 UTC, Kang-kyunghun commented on API/models/productDao.js
> +
이 부분은 점심 이후에 구두로 설명해 드리겠습니다.

2023-04-28 02:33 UTC, Kang-kyunghun requested changes

2023-04-28 02:33 UTC, Kang-kyunghun commented on API/controllers/productController.js
> +    req.query;
이거 적용이 안 되었습니다.

2023-04-28 02:33 UTC, Kang-kyunghun commented on tests/tests/products.test.js
> +    expect(Object.keys(response.body[0])).toEqual([
실제 결과를 테스트 해주세요.

2023-04-29 13:06 UTC, songsong95 commented
![스크린샷 2023-04-29 21-57-50](https://user-images.githubusercontent.com/120084509/235303978-eaa9dbfa-2054-4401-95be-4077875753f7.png)

file:///home/song137/%EC%82%AC%EC%A7%84/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7/%EC%8A%A4%ED%81%AC%EB%A6%B0%EC%83%B7%202023-04-29%2022-04-46.png

2023-04-30 12:52 UTC, merged